web:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ./src:/src
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
      - php
php:
  build: .
  volumes:
    - ./src:/src
  links:
    - mariadb

mariadb:
  image: mariadb:latest
  volumes:
    - ./db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=test123

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mariadb:db
  ports:
    - "8082:80"
  environment:
    - PMA_USER=root
    - PMA_PASSWORD=test123
    - PHP_UPLOAD_MAX_FILESIZE=100MB
